//** This file was code generated by got. ***

package old

import (
	"bytes"
)

func drawBuilder(buf *bytes.Buffer) (err error) {

	buf.WriteString(`<html>
<head>
</head>
<body>
    <h1>Goradd Builder</h1>
    <p>
    `)

	buf.WriteString(textToHtml(results))

	buf.WriteString(`
    </p>
    `)
	if stop {
		buf.WriteString(`<p><a href="/builder?cmd=`)

		buf.WriteString(cmd)

		buf.WriteString(`">Restart<a></p>`)
	}

	buf.WriteString(`    `)
	if stop {
		buf.WriteString(`<p><a href="/">Return to Start Page<a></p>`)
	}

	buf.WriteString(`</body>
</html>
`)

	if !stop {

		buf.WriteString(`<script>
setTimeout(function() {
    location = "/builder";  // Refresh
}, 2000);
</script>
`)

	}

	return
}
