//** This file was code generated by got. DO NOT EDIT. ***

package controls

import (
	"bytes"
	"context"

	"github.com/goradd/goradd/pkg/page"
)

func (form *ControlsForm) AddHeadTags() {
	form.FormBase.AddHeadTags()
	if "Control Examples" != "" {
		form.Page().SetTitle("Control Examples")
	}

	// double up to deal with body attributes if they exist
	form.Page().BodyAttributes = `
`
}

func (form *ControlsForm) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
`)
	path := page.GetContext(ctx).HttpContext.URL.Path
	buf.WriteString(`
<h1>Control Examples</h1>
<div class="controlList_scroll">
  <ul>
    <li><a href="`)

	buf.WriteString(path)

	buf.WriteString(`">Home</a></li>
    <li><a href="`)

	buf.WriteString(path)

	buf.WriteString(`?control=textbox">Textboxes: Textbox, IntegerTextbox, FloatTextbox</a></li>
  </ul>
</div>
<div class="detail_container">
	`)

	buf.WriteString(`
`)

	{
		err := form.detail.Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
</div>
`)

	buf.WriteString(`
`)

	return
}
