//** This file was code generated by GoT. DO NOT EDIT. ***

package welcome

import (
	"context"
	"io"
)

func (ctrl *CodegenForm) AddHeadTags() {
	ctrl.FormBase.AddHeadTags()
	if "Code Generate" != "" {
		ctrl.Page().SetTitle("Code Generate")
	}

	// deal with body attributes too
	ctrl.Page().BodyAttributes = `
`
}

func (ctrl *CodegenForm) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `<h1>CodeGenerator</h1>
`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("infoPanel").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("infoPanel").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `<p>
If codegen succeeded, exit and restart the app by executing <b>go run goradd-project/main</b>
</p>
`); err != nil {
		return
	}

	return
}
