//** This file was code generated by got. ***

package buildtools

import (
	"bytes"
)

func drawInstall(buf *bytes.Buffer) (err error) {

	buf.WriteString(`<html>
<head>
</head>
<body>
    <h1>Goradd Installer</h1>
    <p>
    Installing...
    </p>
    <p>
    `)

	buf.WriteString(textToHtml(results))

	buf.WriteString(`
    </p>
</body>
</html>
`)

	if !stop {

		buf.WriteString(`<script>
setTimeout(function() {
    location = "/install";  // Refresh
}, 2000);
</script>
`)

	}

	return
}
