//** This file was code generated by got. ***

package template

import (
	"bytes"
	"goradd/config"

	"github.com/spekary/goradd/codegen/generator"
	"github.com/spekary/goradd/orm/db"
	"github.com/spekary/goradd/util"
)

func init() {
	t := ConnectorTemplate{
		generator.Template{
			Overwrite: false,
			TargetDir: config.LocalDir + "/gen",
		},
	}
	generator.AddTableTemplate(&t)
}

type ConnectorTemplate struct {
	generator.Template
}

func (n *ConnectorTemplate) FileName(key string, t generator.TableType) string {
	return n.TargetDir + "/" + key + "/connector/" + t.GoName + ".go"
}

func (n *ConnectorTemplate) GenerateTable(codegen generator.Codegen, dd *db.DatabaseDescription, t generator.TableType, buf *bytes.Buffer) {
	//connector.tmpl

	// The master template for the connector classes

	var privateName = util.LcFirst(t.GoName)

	buf.WriteString(`package connector

// This is the connector override. Feel free to edit.

type `)

	buf.WriteString(t.GoName)

	buf.WriteString(` struct {
    `)

	buf.WriteString(privateName)

	buf.WriteString(`Base
}

`)

}

func (n *ConnectorTemplate) Overwrite() bool {
	return n.Template.Overwrite
}
