//** This file was code generated by GoT. DO NOT EDIT. ***

package panels

import (
	"context"
	"io"
)

// DrawTemplate draws the content of the matching control's template file.
func (ctrl *CheckboxPanel) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `<h2>Checkboxes and Radio Buttons</h2>
<p>
Checkboxes and RadioButtons create html input tags with a type of "checkbox" or "radio".
They are used for setting true/false values, or for selecting from a group of items.
`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Goradd&#39;s`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, ` code generation uses checkboxes to set binary values in a database, and
uses a checkbox list to setup relationships between records in a one-to-many relationship.
</p>
<p>
See also the CheckboxList and RadioList controls for working with groups of these controls,
and the CheckboxColumn for working with a column of checkboxes in an html table.
</p>
<h3>Labels</h3>
<p>
Dealing with labels and checkboxes can be tricky. Html uses a `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `&lt;label&gt;`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, ` tag to associate text
with a checkbox. The problem is that `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `&lt;label&gt;`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, ` tags are also used in html to associate titles
with input elements like textboxes and select lists. What if you want both a title, and a checkbox
label? You need two labels!
</p>
<p>
The problem is compounded by the many ways a label can be placed next to a checkbox. A label can
come before or after a checkbox, and also wrap around the checkbox. Different CSS and JS frameworks
require different placement of the label to correctly do their styling. In fact,
<a href="http://www.getbootstrap.com">Bootstrap</a>, a popular CSS framework, changed its placement
requirement between versions 3 and 4.
</p>
<p>
Goradd gives you the flexibility to place your labels where you want, and also gives you
a global setting to default the label placement across your whole site. The Goradd Bootstrap
support will automatically do the correct thing for Bootstrap.
</p>
<p>
In the examples below, view the source html of the page to see how Goradd deals with labels on
checkboxes.
</p>
`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("checkbox1-ff").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("checkbox1-ff").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("checkbox2-ff").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("checkbox2-ff").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `

<h3>Radio Buttons</h3>
Radio buttons are generally part of a group of buttons with the purpose of allowing the user
to select only one item from the group. You choose whatever group name you want and assign it to
each button. The browser will then make sure only one gets selected.
<fieldset style="width:200px;">
<legend>Place</legend>
`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("radio1").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("radio1").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("radio2").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("radio2").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("radio3").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("radio3").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("infoPanel").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("infoPanel").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `</fieldset>

`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("ajaxButton").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("ajaxButton").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("serverButton").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("serverButton").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	return
}
