//** This file was code generated by got. DO NOT EDIT. ***

package panels

import (
	"bytes"
	"context"
)

func (ctrl *DefaultPanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<h1>ControlBase Examples</h1>
<p>
These pages demonstrate the various supported controls that are available in goradd. These
controls fall in to these categories:
</p>
<ul>
<li>Standard html tags, like `)

	buf.WriteString(`&lt;input&gt;`)

	buf.WriteString(` or `)

	buf.WriteString(`&lt;div&gt;`)

	buf.WriteString(` tags</li>
<li>Custom controls that let you edit database data types, like an Integer or Date field</li>
<li>Custom controls that let you create database relationships, like one-to-many relationships</li>
<li>Useful controls for dealing with common situations</li>
<li>Controls corresponding to widgets found in supported css/js libraries, like Bootstrap</li>
</ul>
<p>
The goal of these pages is to try to demonstrate many of the options available with these controls
and give you examples of how to use them. They are also used by our testing system to exercise these
controls during our unit tests.
</p>
<p>
Click on the items on the left to go to the various demonstration pages.
</p>
`)

	buf.WriteString(`
`)

	return
}
