//** This file was code generated by GoT. DO NOT EDIT. ***

package panels

import (
	"context"
	"io"
)

func (ctrl *ImageCapturePanel) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `<h2>Image Capture Widget</h2>
<p>
The ImageCapture widget captures images from devices that have a camera, and is an example of a GoRADD control
that has additional javascript to help it work. The example below clips the image with a circle, which is a common
thing to do when capturing images for chat groups and messaging applications.
</p>
<p>
After capturing the image once, reload the page. You will see that the image is preserved, and makes a round-trip
from the original capture, to the server, and then when you reload the page, it is sent back to the browser.
</p>

`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("ic1-ff").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("ic1-ff").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	return
}
