//** This file was code generated by GoT. DO NOT EDIT. ***

package panels

import (
	"context"
	"io"
)

// DrawTemplate draws the contents of the ProjectPanel panel.
func (p *ProjectPanel) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `    <h4>Project Details</h4>
`); err != nil {
		return
	}

	if p.project != nil {

		if _, err = io.WriteString(_w, `    <table>
    <tr id="nameItem"><th>Name</th><td>`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, p.project.Name()); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `</td></tr>
    <tr><th>Description</th><td>`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, p.project.Description()); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `</td></tr>
    <tr><th>Budget</th><td>`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, p.project.Budget()); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `</td></tr>
    <tr><th>Spent</th><td>`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, p.project.Spent()); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `</td></tr>
    <tr><th>Manager</th><td>`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, p.project.LoadManager(ctx).FirstName()+" "+p.project.LoadManager(ctx).LastName()); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `</td></tr>
    </table>
`); err != nil {
			return
		}

	}

	return
}
