//** This file was code generated by got. DO NOT EDIT. ***

package panels

import (
	"bytes"
	"context"
)

// DrawTemplate draws the contents of the ProjectPanel panel.
func (p *ProjectPanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`    <h4>Project Details</h4>
`)
	if p.project != nil {
		buf.WriteString(`    <div id="nameItem"><label>Name</label>`)

		buf.WriteString(p.project.Name())

		buf.WriteString(`</div>
    <div><label>Description</label>`)

		buf.WriteString(p.project.Description())

		buf.WriteString(`</div>
    <div><label>Budget</label>`)

		buf.WriteString(p.project.Budget())

		buf.WriteString(`</div>
    <div><label>Spent</label>`)

		buf.WriteString(p.project.Spent())

		buf.WriteString(`</div>
    <div><label>Manager</label>`)

		buf.WriteString(p.project.LoadManager(ctx).FirstName() + " " + p.project.LoadManager(ctx).LastName())

		buf.WriteString(`</div>
`)
	}

	return
}
