//** This file was code generated by got. DO NOT EDIT. ***

package panels

import (
	"bytes"
	"context"
)

func (ctrl *RepeaterPanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<h1>Repeaters</h1>
<p>
The Repeater control repeats an HTML snippet of code once for each item of data you provide.
It is similar to a table, which creates a table row for each item of data, but it lets you repeat
custom html. You can base the html on a string you create, or on a GOT template.
</p>
<p>
Repeaters can use Pagers to control which data items are shown in the repeater.
</p>
`)

	buf.WriteString(`
`)

	{
		err := ctrl.Page().GetControl("pager1").Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := ctrl.Page().GetControl("repeater1").Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	return
}
