//** This file was code generated by GoT. DO NOT EDIT. ***

package panels

import (
	"context"
	"io"

	"github.com/goradd/goradd/pkg/log"
	"github.com/goradd/goradd/pkg/orm/db"
)

// DrawTemplate draws the content of the matching control's template file.
func (ctrl *TableProxyPanel) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `<style>
table {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

table td, table th {
  border: 1px solid #ddd;
  padding: 8px;
}

table tr:nth-child(even){background-color: #f2f2f2;}

table tr:hover {background-color: #ddd;}

table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>
<h2>Tables - Proxy Column</h2>
<p>
The table below demonstrates how to combine a Proxy, a CustomColumn, and a Panel to display a list of records
that allow you to click on a record to see detail of the record.
</p>
`); err != nil {
		return
	}

	if db.GetDatabase("goradd") == nil {

		if _, err = io.WriteString(_w, `<h3 style="color:red">Error</h3>
<p>You have not installed the goradd example database. See the examples/readme.txt file for instructions.<p>
`); err != nil {
			return
		}
		log.Error("goradd database not installed.")
	} else {

		if `` == "" {

			if _, err = io.WriteString(_w, `    `); err != nil {
				return
			}
			ctrl.Page().GetControl("table1").Draw(ctx, _w)
			if _, err = io.WriteString(_w, `
`); err != nil {
				return
			}

		} else {

			if _, err = io.WriteString(_w, `    `); err != nil {
				return
			}
			ctrl.Page().GetControl("table1").ProcessAttributeString(``).Draw(ctx, _w)
			if _, err = io.WriteString(_w, `
`); err != nil {
				return
			}

		}

		if `` == "" {

			if _, err = io.WriteString(_w, `    `); err != nil {
				return
			}
			ctrl.Page().GetControl("personPanel").Draw(ctx, _w)
			if _, err = io.WriteString(_w, `
`); err != nil {
				return
			}

		} else {

			if _, err = io.WriteString(_w, `    `); err != nil {
				return
			}
			ctrl.Page().GetControl("personPanel").ProcessAttributeString(``).Draw(ctx, _w)
			if _, err = io.WriteString(_w, `
`); err != nil {
				return
			}

		}

		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	return
}
