//** This file was code generated by got. DO NOT EDIT. ***

package orm

import (
	"bytes"
	"context"

	"github.com/goradd/goradd/web/examples/gen/goradd/model"
	"github.com/goradd/goradd/web/examples/gen/goradd/model/node"
)

func (ctrl *OneOnePanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<h1>One-to-One Relationships</h1>
<p>
By creating a unique index on a foreign key, you will create a one-to-one relationship.
One-to-one relationships link two records with each record being an extension of the other.
You can use this to model subclasses, extend a record with optional values, or to improve search results, allowing the database
to retrieve only the main record on an initial search, and then the extended record if more detail is desired of
a particular record.
</p>
<p>
In the example below, we load a login, and then examine which person the login belongs to.
`)
	login := model.LoadLogin(ctx, "2", node.Login().Person())

	buf.WriteString(`</p>
<p>
    Person for Login `)

	buf.WriteString(login.Username())

	buf.WriteString(`: `)

	buf.WriteString(login.Person().FirstName())

	buf.WriteString(` `)

	buf.WriteString(login.Person().LastName())

	buf.WriteString(` <br>
</p>
<p>
Here, we traverse the relationship in the other direction, loading the person first, and then getting the login.
`)
	person := model.LoadPerson(ctx, "3", node.Person().Login())

	buf.WriteString(`</p>
<p>
    Login for `)

	buf.WriteString(person.FirstName())

	buf.WriteString(` `)

	buf.WriteString(person.LastName())

	buf.WriteString(`: `)

	buf.WriteString(person.Login().Username())

	buf.WriteString(`  <br>
</p>

<h2>Creating One-to-One Linked Records</h2>

`)

	buf.WriteString(`
`)

	return
}
