//** This file was code generated by got. DO NOT EDIT. ***

package panels

import (
	"bytes"
	"context"

	"github.com/goradd/goradd/pkg/page"
)

func (control *TextboxPanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<h1>Textboxes</h1>
<p>
Built-in Textboxes come in three flavors:
</p>
<ul>
<li>Plain</li>
<li>Integer: Validating that the input is an integer in a specific range.</li>
<li>Float: Validating that the input is a floating-point number in a specific range.</li>
</ul>
<h2>Demos</h2>
<p>Click on one of the Submit buttons to cause the controls to validate.</p>
`)

	buf.WriteString(`
`)

	{
		err := control.PlainText.With(page.NewLabelWrapper()).Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := control.IntegerText.With(page.NewLabelWrapper()).Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := control.FloatText.With(page.NewLabelWrapper()).Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := control.SubmitAjax.Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := control.SubmitServer.Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	return
}
