//** This file was code generated by got. DO NOT EDIT. ***

package page

import (
	"bytes"
	"context"
)

func (form *TestTextboxForm) AddHeadTags() {
	form.FormBase.AddHeadTags()
	if "Textbox Tests" != "" {
		form.Page().SetTitle("Textbox Tests")
	}

	// double up to deal with body attributes if they exist
	form.Page().BodyAttributes = ``
}

func (form *TestTextboxForm) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`

`)

	buf.WriteString(`
`)

	{
		err := form.PlainText.Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`

`)

	buf.WriteString(`
`)

	return
}
