//** This file was code generated by got. DO NOT EDIT. ***

package panels

import (
	"bytes"
	"context"
)

func (ctrl *DefaultPanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<h1>Bootstrap ControlBase Examples</h1>
<p>
These pages demonstrate some of the supported <a href="http://getbootstrap.com">Bootstrap</a> controls that are
available in goradd. It is not an exhaustive recreation of the Bootstrap documentation, so you
can likely do a lot more with Bootstrap than you see here.
</p>
<p>
Click the menu to see the list of examples.
</p>
`)

	buf.WriteString(`
`)

	return
}
