//** This file was code generated by GoT. DO NOT EDIT. ***

package panels

import (
	"context"
	"io"

	. "github.com/goradd/goradd/pkg/bootstrap/control"
	"github.com/goradd/goradd/pkg/page/control"
)

func (ctrl *Forms2Panel) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `
<h2>Inline Form Layout</h2>
<p>
This is an example of a typical form with inline labels.
</p>

`); err != nil {
		return
	}

	if ctrl.Page().HasControl("nameText-fg") {
		ctrl.Page().GetControl("nameText-fg").(control.LabelAttributer).LabelAttributes().MergeString(`class="col-form-label col-2"`)
	}

	if ctrl.Page().HasControl("nameText-fg") {
		ctrl.Page().GetControl("nameText-fg").(FormGroupI).InnerDivAttributes().MergeString(`class="col-10"`)
	}

	if `class="row mb-3"` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("nameText-fg").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("nameText-fg").ProcessAttributeString(`class="row mb-3"`).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if ctrl.Page().HasControl("streetText-fg") {
		ctrl.Page().GetControl("streetText-fg").(control.LabelAttributer).LabelAttributes().MergeString(`class="col-form-label col-2"`)
	}

	if ctrl.Page().HasControl("streetText-fg") {
		ctrl.Page().GetControl("streetText-fg").(FormGroupI).InnerDivAttributes().MergeString(`class="col-10"`)
	}

	if `class="row mb-3"` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("streetText-fg").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("streetText-fg").ProcessAttributeString(`class="row mb-3"`).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `<div class="row align-items-center mb-3">
    <div class="col-6">
        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if ctrl.Page().HasControl("cityText-fg") {
		ctrl.Page().GetControl("cityText-fg").(control.LabelAttributer).LabelAttributes().MergeString(`class="col-form-label col-4"`)
	}

	if _, err = io.WriteString(_w, `        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if ctrl.Page().HasControl("cityText-fg") {
		ctrl.Page().GetControl("cityText-fg").(FormGroupI).InnerDivAttributes().MergeString(`class="col-8"`)
	}

	if _, err = io.WriteString(_w, `        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if `class="row"` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("cityText-fg").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("cityText-fg").ProcessAttributeString(`class="row"`).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `    </div>
    <div class="col-2">
        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if ctrl.Page().HasControl("stateText-fg") {
		ctrl.Page().GetControl("stateText-fg").(control.LabelAttributer).LabelAttributes().MergeString(`class="col-form-label col-6"`)
	}

	if _, err = io.WriteString(_w, `        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if ctrl.Page().HasControl("stateText-fg") {
		ctrl.Page().GetControl("stateText-fg").(FormGroupI).InnerDivAttributes().MergeString(`class="col-6"`)
	}

	if _, err = io.WriteString(_w, `        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if `class="row"` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("stateText-fg").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("stateText-fg").ProcessAttributeString(`class="row"`).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `    </div>
    <div class="col-4">
        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if ctrl.Page().HasControl("zipText-fg") {
		ctrl.Page().GetControl("zipText-fg").(control.LabelAttributer).LabelAttributes().MergeString(`class="col-form-label col-4"`)
	}

	if _, err = io.WriteString(_w, `        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if ctrl.Page().HasControl("zipText-fg") {
		ctrl.Page().GetControl("zipText-fg").(FormGroupI).InnerDivAttributes().MergeString(`class="col-8"`)
	}

	if _, err = io.WriteString(_w, `        `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if `class="row"` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("zipText-fg").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("zipText-fg").ProcessAttributeString(`class="row"`).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `    </div>
</div>

`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `<div class="row">
`); err != nil {
		return
	}

	if "2" == "" {

		if _, err = io.WriteString(_w, `<div class="col">
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `<div class="col-2">
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `</div>
`); err != nil {
		return
	}

	if "10" == "" {

		if _, err = io.WriteString(_w, `<div class="col">
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `<div class="col-10">
`); err != nil {
			return
		}

	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("ajaxButton").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("ajaxButton").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("serverButton").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Page().GetControl("serverButton").ProcessAttributeString(``).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `</div>
`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `</div>
`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	return
}
