//** This file was code generated by got. ***

package control

import (
	"bytes"
	"context"
	"html"
)

func (d *Modal) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`    <div class="modal-dialog" role="document">
        <div class="modal-content">
`)

	d.titleBar.AddClass("modal-header")
	d.titleBar.Draw(ctx, buf)

	buf.WriteString(`            <div class="modal-body">
`)

	l := len(d.Children())
	if l > 2 {
		for _, child := range d.Children() {
			if child.ID() != d.titleBar.ID() && child.ID() != d.buttonBar.ID() {
				child.Draw(ctx, buf)
			}
		}
	} else {

		buf.WriteString(`<p>`)

		buf.WriteString(html.EscapeString(d.Text()))

		buf.WriteString(` </p>`)

	}

	buf.WriteString(`            </div>
`)

	d.buttonBar.AddClass("modal-footer")
	d.buttonBar.Draw(ctx, buf)

	buf.WriteString(`        </div>
    </div>

`)

	return
}

func (d *TitleBar) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {
	if d.title != "" {

		buf.WriteString(`     <h5 id="`)

		buf.WriteString(d.Parent().ID())

		buf.WriteString(`_title" class="modal-title">`)

		buf.WriteString(d.title)

		buf.WriteString(`</h5>
`)

	}
	if d.hasCloseBox {

		buf.WriteString(`    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
`)

	}
	return
}
