//** This file was code generated by GoT. DO NOT EDIT. ***

package browsertest

import (
	"context"
	"io"
)

func (ctrl *JsUnitForm) AddHeadTags() {
	ctrl.FormBase.AddHeadTags()
	if "Goradd JavaScript Unit Test" != "" {
		ctrl.Page().SetTitle("Goradd JavaScript Unit Test")
	}

	// deal with body attributes too
	ctrl.Page().BodyAttributes = ``
}

func (ctrl *JsUnitForm) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `<h1>JavaScript Unit Tests</h1>
`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}

		if err = ctrl.Page().GetControl("startButton").Draw(ctx, _w); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}

		if err = ctrl.Page().GetControl("startButton").ProcessAttributeString(``).Draw(ctx, _w); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `<h3>Results</h3>
`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}

		if err = ctrl.Page().GetControl("results").Draw(ctx, _w); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}

		if err = ctrl.Page().GetControl("results").ProcessAttributeString(``).Draw(ctx, _w); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `<h3>Test Space</h3>
<p id = "intro">
The area below is used by the unit test code to exercise the code.
</p>
<div id="testspace">
<p id="testP">
I am here
</p>
<div id="testD" data-animal-type="bird" spellcheck>
a div
</div>
</div>
<ul id="listener"><li id="outer"><span id="inner">a span</span></li></ul>

`); err != nil {
		return
	}

	return
}
