//** This file was code generated by got. DO NOT EDIT. ***

package browsertest

import (
	"bytes"
	"context"
)

func (form *TestForm) AddHeadTags() {
	form.FormBase.AddHeadTags()
	if "Tests" != "" {
		form.Page().SetTitle("Tests")
	}

	// double up to deal with body attributes if they exist
	form.Page().BodyAttributes = ``
}

func (form *TestForm) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<h1>Browser Based Tests</h1>
`)

	buf.WriteString(`
`)

	{
		err := form.Page().GetControl("test-list").Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := form.Page().GetControl("run-button").Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := form.Page().GetControl("run-all-button").Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
<div>
Currently running:
`)

	buf.WriteString(`
`)

	{
		err := form.Page().GetControl("running-label").Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	buf.WriteString(`
`)

	{
		err := form.Page().GetControl("controller").Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
</div>
`)

	buf.WriteString(`
`)

	return
}
