//** This file was code generated by got. DO NOT EDIT. ***

package tutorial

import (
	"bytes"
	"context"
)

func (ctrl *DefaultPanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<h1>Tutorial</h1>
<p>
Welcome to the GoRADD tutorial. These pages will help you learn about:
</p>
<ul>
<li>The GoRADD Object-Relation Model (ORM), and how to use the generated code to read and write to your database.</li>
<li>The form engine, and how to create dynamic html pages only using GO code.</li>
<li>Additional support libraries</li>
</ul>
<p>
Click on the items on the left to go to the various demonstration pages.
</p>
`)

	buf.WriteString(`
`)

	return
}
