//** This file was code generated by got. DO NOT EDIT. ***

package tutorial

import (
	"bytes"
	"context"
	"html"
	"io/ioutil"
)

func (control *FilePanel) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
<figure>
<figcaption>`)

	buf.WriteString(control.base)

	buf.WriteString(`</figcaption>
<pre>
<code>
`)
	var content string

	if control.file != "" {
		data, err := ioutil.ReadFile(control.file)
		if err == nil {
			content = html.EscapeString((string(data)))
		}
	}

	buf.WriteString(content)

	buf.WriteString(`
</code>
</pre>
</figure>
`)

	buf.WriteString(`
`)

	return
}
