//** This file was code generated by got. DO NOT EDIT. ***

package tutorial

import (
	"bytes"
	"context"

	"github.com/goradd/goradd/pkg/page"
)

func (form *IndexForm) AddHeadTags() {
	form.FormBase.AddHeadTags()
	if "Tutorial" != "" {
		form.Page().SetTitle("Tutorial")
	}

	// double up to deal with body attributes if they exist
	form.Page().BodyAttributes = `
`
}

func (form *IndexForm) DrawTemplate(ctx context.Context, buf *bytes.Buffer) (err error) {

	buf.WriteString(`
`)
	path := page.GetContext(ctx).HttpContext.URL.Path
	buf.WriteString(`
<h1>Control Examples</h1>
`)

	buf.WriteString(`
`)

	{
		err := form.viewSourceButton.Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
<div class="sidebar">
<h2>ORM</h2>
  <ul>
`)
	for _, pr := range pages["orm"] {
		buf.WriteString(`    <li><a href="`)

		buf.WriteString(path)

		buf.WriteString(`?pageID=orm-`)

		buf.WriteString(pr.id)

		buf.WriteString(`">`)

		buf.WriteString(pr.title)

		buf.WriteString(`</a></li>
`)
	}

	buf.WriteString(`  </ul>
</div>
<div class="detail_container">
	`)

	buf.WriteString(`
`)

	{
		err := form.detailPanel.Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
</div>
<div class="source_container">
	`)

	buf.WriteString(`
`)

	{
		err := form.sourcePanel.Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
</div>

`)

	buf.WriteString(`
`)

	return
}
