//** This file was code generated by got. ***

package page

import (
	"bytes"
	"context"
)

func PageTmpl(ctx context.Context, page *Page, buf *bytes.Buffer) (err error) {

	buf.WriteString(`<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
`)
	page.DrawHeaderTags(ctx, buf)
	buf.WriteString(`</head>
<body>
`)

	{
		err := page.Form().Draw(ctx, buf)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`</body>
</html>

`)

	return

}
