//** This file was code generated by got. ***

package page

import (
	"bytes"
	"context"
)

func NameTmpl(ctx context.Context, ctrl ControlI, html string, buf *bytes.Buffer) {

	buf.WriteString(`<div id="`)

	buf.WriteString(ctrl.Id())

	buf.WriteString(`_ctl" `)

	buf.WriteString(ctrl.WrapperAttributes().String())

	buf.WriteString(` >
`)
	if ctrl.Name() != "" {
		buf.WriteString(`    <label id="`)

		buf.WriteString(ctrl.Id())

		buf.WriteString(`_name" class="goradd-name"`)
		if ctrl.HasFor() {
			buf.WriteString(` for="`)

			buf.WriteString(ctrl.Id())

			buf.WriteString(`" `)
		}
		buf.WriteString(`>`)

		buf.WriteString(ctrl.Name())

		buf.WriteString(`</label>
`)
	}
	buf.WriteString(`    `)

	buf.WriteString(html)

	buf.WriteString(`
    <div id="`)

	buf.WriteString(ctrl.Id())

	buf.WriteString(`_err" class="goradd-err">`)

	buf.WriteString(ctrl.ValidationError())

	buf.WriteString(`</div>
`)
	if ctrl.Instructions() != "" {
		buf.WriteString(`    <div class="goradd-instructions">`)

		buf.WriteString(ctrl.Instructions())

		buf.WriteString(`</div>
`)
	}
	buf.WriteString(`</div>
`)

	return

}
