name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        db: [mariadb]
    env:
      GOFLAGS: -mod=mod
      ROOT_DB_USER: root
      DB_USER: tester
    steps:
    - name: Setup Windows Environment
      if: ${{ runner.os == 'Windows' }}
      run: echo "home=$HOME" >> $env:GITHUB_ENV
      
    - name: Setup Linux Environment
      if: ${{ runner.os == 'Linux' }}
      run: echo "home=$HOME" >> $GITHUB_ENV
      
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Start MariaDB
      if: ${{ matrix.db == 'mariadb' }}
      uses: ankane/setup-mariadb@v1
      with:
        database: goradd

    - name: Setup Databases
      run: |
        mysqladmin -u${{ env.ROOT_DB_USER }}  create goradd_unit
        mysql -u${{ env.ROOT_DB_USER }} -e "CREATE USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED BY ''"
        mysql -u${{ env.ROOT_DB_USER }} -e "GRANT ALL PRIVILEGES ON *.* TO '${{ env.DB_USER }}'@'localhost'"
        mysql -u${{ env.ROOT_DB_USER }} -e "FLUSH PRIVILEGES"
        mysql -u${{ env.ROOT_DB_USER }} -e 'source ./web/examples/db/mysql.sql;' goradd
        mysql -u${{ env.ROOT_DB_USER }} -e 'source ./internal/ci/db/goradd_unit.mysql.sql;' goradd_unit

    - name: Build
      run: go install

    - name: Install
      working-directory: ${{ env.home }}
      run: |
       goradd install
       cp -r ${{ github.workspace }}/internal/ci/goradd-test .
       mv ./goradd-test/gomod.txt ./goradd-test/go.mod
       echo "replace github.com/goradd/goradd => ${{ github.workspace }}" >> ./goradd-project/go.mod
       echo "replace github.com/goradd/goradd => ${{ github.workspace }}" >> ./goradd-test/go.mod

    - name: Codegen
      working-directory: ${{ env.home }}/goradd-test/codegen
      run: go generate build.go

    - name: Unit Test Packages
      working-directory: ${{ env.home }}/goradd-project
      run: go test github.com/goradd/goradd/pkg/...

    - name: Unit Test Database
      working-directory: ${{ env.home }}/goradd-test/dbtest
      run: go test

    - name: Browser Based Test
      working-directory: ${{ env.home }}/goradd-test
      run: go test




