name: Unit Tests And MariaDB Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      ROOT_DB_USER: root
      DB_USER: tester
    steps:
    - uses: actions/checkout@v3
      with:
        path: goradd-src

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.2'

    - name: Install goradd
      working-directory: ./goradd-src
      run: go install

    - name: Install goradd-project
      working-directory: .
      run: |
        goradd install

    - name: Unit test packages
      working-directory: ./goradd-src
      run: go test github.com/goradd/goradd/pkg/...

    - name: Start MariaDB
      uses: ankane/setup-mariadb@v1
      with:
        database: goradd

    - name: Setup Maria Databases
      run: |
        mysqladmin -u${{ env.ROOT_DB_USER }}  create goradd_unit
        mysql -u${{ env.ROOT_DB_USER }} -e "CREATE USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED BY ''"
        mysql -u${{ env.ROOT_DB_USER }} -e "GRANT ALL PRIVILEGES ON *.* TO '${{ env.DB_USER }}'@'localhost'"
        mysql -u${{ env.ROOT_DB_USER }} -e "FLUSH PRIVILEGES"
        mysql -u${{ env.ROOT_DB_USER }} -e 'source ./goradd-src/web/examples/db/mysql.goradd.sql;' goradd
        mysql -u${{ env.ROOT_DB_USER }} -e 'source ./goradd-src/internal/ci/db/mysql.goradd_unit.sql;' goradd_unit

    - name: Setup MariaDB Init file
      working-directory: ./goradd-project/config
      run: |
        cp ${{ github.workspace }}/goradd-src/internal/ci/goradd-test/config/initMysql.go ./db.go

    - name: Install goradd-test
      working-directory: .
      run: |
        cp ${{ github.workspace }}/goradd-src/internal/ci/go.work .
        cp -r ${{ github.workspace }}/goradd-src/internal/ci/goradd-test .
        cd goradd-test
        go mod tidy

    - name: Codegen
      working-directory: ./goradd-test/codegen
      run: go generate build.go

    - name: Unit Test Database
      working-directory: ./goradd-test/dbtest
      run: go test

    - name: Browser Based Test
      working-directory: ./goradd-test
      run: go test




