name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ROOT_DB_USER: root
      DB_USER: tester
    steps:
      - uses: actions/checkout@v3
        with:
          path: goradd-src

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install goradd
        working-directory: ${{ github.workspace }}/goradd-src
        run: go install

      - name: Install goradd-project
        working-directory: ${{ github.workspace }}
        run: |
          goradd install

      - name: Start PostgresDB
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'goradd'
          postgresql user: '${{ env.ROOT_DB_USER }}'

      - name: Setup Postgres Databases
        run: |
          createdb -U '${{ env.DB_USER }}' goradd_unit
          createuser -U '${{ env.DB_USER }}' -w '${{ env.DB_USER }}'
          psql -U ${{ env.ROOT_DB_USER }} -e "GRANT ALL PRIVILEGES ON *.* TO '${{ env.DB_USER }}'@'localhost'"
          psql -U ${{ env.ROOT_DB_USER }} -d goradd -a -f './goradd-src/web/examples/db/pg.goradd.sql'
          psql -U ${{ env.ROOT_DB_USER }} -d goradd_unit -a -f './goradd-src/internal/ci/db/pg.goradd_unit.sql'

      - name: Setup Postgres Init file
        working-directory: ${{ github.workspace }}/goradd-project/config
        run: |
          cp ${{ github.workspace }}/goradd-src/internal/ci/goradd-test/config/initPostgres.go ./db.go

      - name: Install goradd-test
        working-directory: ${{ github.workspace }}
        run: |
          cp ${{ github.workspace }}/goradd-src/internal/ci/go.work .
          cp -r ${{ github.workspace }}/goradd-src/internal/ci/goradd-test .
          cd goradd-test
          go mod tidy

      - name: Codegen
        working-directory: ${{ github.workspace }}/goradd-test/codegen
        run: go generate build.go

      - name: Unit Test Database
        working-directory: ${{ github.workspace }}/goradd-test/dbtest
        run: go test




