//** This file was code generated by got. ***

package template

import (
	"bytes"
	"goradd/config"

	"github.com/spekary/goradd/codegen/generator"
	"github.com/spekary/goradd/orm/db"
	"github.com/spekary/goradd/util"
)

func init() {
	t := ModelTemplate{
		generator.Template{
			Overwrite: false,
			TargetDir: config.LocalDir + "/gen",
		},
	}
	generator.AddTableTemplate(&t)
}

type ModelTemplate struct {
	generator.Template
}

func (n *ModelTemplate) FileName(key string, t *db.TableDescription) string {
	return n.TargetDir + "/" + key + "/model/" + t.GoName + ".go"
}

func (n *ModelTemplate) GenerateTable(codegen generator.Codegen, dd *db.DatabaseDescription, t *db.TableDescription, buf *bytes.Buffer) {
	// The master template for the model classes

	buf.WriteString(`package model

type `)

	buf.WriteString(t.GoName)

	buf.WriteString(` struct {
	`)

	buf.WriteString(util.LcFirst(t.GoName))

	buf.WriteString(`Base
}

`)

}

func (n *ModelTemplate) Overwrite() bool {
	return n.Template.Overwrite
}
