//** This file was code generated by got. ***

package page

import (
	"bytes"
	"context"
	"github.com/spekary/goradd/pkg/html"
)

func DivTmpl(ctx context.Context, ctrl ControlI, h string, buf *bytes.Buffer) {

	buf.WriteString(`<div id="`)

	buf.WriteString(ctrl.ID())

	buf.WriteString(`_ctl" `)

	buf.WriteString(ctrl.WrapperAttributes().String())

	buf.WriteString(` >
`)

	buf.WriteString(html.Indent(h))

	buf.WriteString(`
</div>
`)

	return
}
